// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	errs "github.com/energywork/pseudo-paysystem/lib/errs"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/energywork/pseudo-paysystem/balance/internal/repository"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *Repository) Create(_a0 *repository.Balance) *errs.Error {
	ret := _m.Called(_a0)

	var r0 *errs.Error
	if rf, ok := ret.Get(0).(func(*repository.Balance) *errs.Error); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*errs.Error)
		}
	}

	return r0
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
